name: Release Buildnote Action
concurrency: release-${{ github.event.inputs.target }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (e.g. 1.0.0)
        required: true
        type: string
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Create
        run: |
          gh release create "v${{ github.event.inputs.version }}" --title "Release v${{ github.event.inputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.BUILDNOTE_ACTION_RELEASE_PAT }}
